### ISSUE TITLE
Fuzzing link goes to 404

### ISSUE THREAD

**Issue by rugk** [richelbilderbeek/travis_cpp_tutorial#26]
```
 * [libFuzzer](https://github.com/richelbilderbeek/cpp/blob/master/content/CppLibFuzzer.md): [a library for coverage-guided fuzz testing](http://llvm.org/docs/LibFuzzer.html)
```

This is 404 error and I also could not find that in your cpp repo. Could only find https://github.com/richelbilderbeek/cpp/blob/master/content/CppFuzzy_equal_to.md

**Comment by richelbilderbeek** [comment]
Thanks again! I've added you to the [list of contributors](https://github.com/richelbilderbeek/travis_cpp_tutorial#contributors) :+1:

**Comment by rugk** [comment]
But where is the content? I was actually interested in it, that's why I clicked the link. :laughing: 

So is it removed or what?

**Comment by richelbilderbeek** [comment]
I've never made a page for the content, as I couldn't get it to work on Travis in the end :disappointed:
