### ISSUE TITLE
CppPerf link broken (404)

### ISSUE THREAD

**Issue by rugk** [richelbilderbeek/travis_cpp_tutorial#27]
https://github.com/richelbilderbeek/cpp/blob/master/content/CppPerf.md is a 404 link in the Readme

**Comment by richelbilderbeek** [comment]
@rugk: thanks! I've added you to [the list of contributors](https://github.com/richelbilderbeek/travis_cpp_tutorial#contributors) for this Issue :+1:

**Comment by rugk** [comment]
But where is the content? I was actually interested in it, that's why I clicked the link. :laughing: 

So is it removed or what?

**Comment by richelbilderbeek** [comment]
I've never made a page for the content, as I couldn't get it to work on Travis in the end :disappointed:
